# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, disko, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ]; 
      kernelModules = [ "dm-snapshot" ];
      luks.devices = {
        crypted = {
          device = "/dev/nvme0n1p3";
          preLVM = true;
        };
      };
    };
    kernelModules = [ "kvm-intel" ];
    kernelParams = [ "acpi_osi=linux" ];
    extraModulePackages = [ ];
    # kernelPackages = lib.mkOverride pkgs.linuxPackages_latest; #pkgs.linuxKernel.kernels.linux_6_2;
    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot.enable = true; 
    };
  };
  disko.devices = import ../modules/disko/luks-lvm.nix {
    disks = [ "/dev/nvme0n1" ];
  };
  networking.useDHCP = lib.mkDefault true;
  
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  
}