{config, lib, pkgs, modulesPath, ... }:

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{
  imports = [ 
      (modulesPath + "/profiles/qemu-guest.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  system.stateVersion = "22.11";
  
  fileSystems."/" = { 
      device = "/dev/disk/by-uuid/40fe3178-6ec1-450f-93fd-c359f2f3daf9";
      fsType = "ext4";
    };

  swapDevices = [  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # This helps stay in step with genertator due to being in vm
  boot = {
    growPartition = true;
    kernelParams = [ "console=ttyS0" ];
    initrd = {
      availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_blk" ];
      kernelModules = [ "kvm-amd" ];
    };
    extraModulePackages = [ ];
    loader = {
      grub = {
        device = "/dev/vda";
      };
      timeout = 0;
    };
  };
  services.qemuGuest.enable = lib.mkDefault true;
}